### ISSUE TITLE
Wakatime does not track Microsoft Edge anymore 

### ISSUE THREAD

**Issue by hardjide** [wakatime/browser-wakatime#261]
Wakatime does not track Microsoft Edge anymore

**Comment by Atko** [comment]
It might be related: in Firefox since  plugin version 3.0.24 it doesn't track times, while it worked perfectly with the plugin version 3.0.22. Of course I've restarted the browser, reinstalled the plugin, disabled every other plugins and so on, but the only solution was to roll back to version 3.0.22.

**Comment by alanhamlett** [comment]
That's probably #280. The fix should be reviewed and update in the Mozilla Addon marketplace soon.

**Comment by alanhamlett** [comment]
For Edge, I just updated WakaTime for Edge to v4.0.0 today, but it might take a few days to be reviewed.

**Comment by Atko** [comment]
@alanhamlett something is still broken. Version 4.0.0 of the firefox plugin under ffox 131.0.0 still doesn't send heartbeats. If it helps: I'm using wakapi.dev, not wakatime.com for storing my worktime.

**Comment by alanhamlett** [comment]
Fixed in v4.0.1. For now I've rolled back the extension to v3.0.22 in the web stores.

**Comment by Atko** [comment]
@alanhamlett it's still broken, bot now I tried to deep dive into the root of the problem and I found the following: when the plugin tries to access https://wakapi.dev/api/ (this is an alternative wakapi server, it's not the "official") it gets a CORS error with the latest versions (3.0.24, 4.0.0, 4.0.1) of the plugin:

[XHR] [POST] https://wakapi.dev/api/users/current/heartbeats.bulk?api_key=(...)

>TypeError: NetworkError when attempting to fetch resource. [WakaTimeCore.ts:249:14](webpack://chrome-wakatime/src/core/WakaTimeCore.ts)
>    sendHeartbeats WakaTimeCore.ts:249
>    handleActivity WakaTimeCore.ts:123
>    <névtelen> background.ts:58

> Cross-Origin request blocked: Same-origin policy does not allow reading remote resource from https://wakapi.dev/api/users/current/heartbeats.bulk?api_key=(...). (Reason: CORS header "Access-Control-Allow-Origin" is missing). Status code: 400.

I don't really know whether it is a problem with wakapi.dev server's config, or it can be fixed on client side, but I hope it can help you to understand the issue.
